trigger:
- master

stages:
- stage: UnitTesting
  jobs:
  - job: DotNetUnitTesting
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo Run your very cool test suite here
  - job: JavascriptUnitTesting
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo The fun is in the js tests

- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      buildConfiguration: 'Release'
      imageName: 'ciberado/dotnetdemo'

    steps:
    - task: DotNetCoreInstaller@0
      displayName: 'Install .net core 3.0 (preview)'
      inputs:
        version: '3.0.100-preview8-013656'
    - script: dotnet publish -c release -o webapp
      displayName: 'dotnet build $(buildConfiguration)'
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'ciberado/dotnetdemo2'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

- stage: Compliance
  jobs:
  - job: ExecuteSecurityCompliance
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo Now trigger that fancy security tool execution
